### ISSUE TITLE
Initializing MyApi using builder giver Exception

### ISSUE THREAD

**Issue by sumitiu** [googleapis/google-api-java-client#1450]
Caused by: java.lang.IllegalStateException: No successful match so far
        at java.util.regex.Matcher.ensureMatch(Matcher.java:1116)
        at java.util.regex.Matcher.group(Matcher.java:382)
        at com.google.api.client.googleapis.GoogleUtils.<clinit>(GoogleUtils.java:66)
        at com.idragonit.backend.myApi.MyApi.<clinit>(MyApi.java:46) 
Version Using: implementation 'com.google.api-client:google-api-client:1.30.6'
in my andoid backed library
In GoogleUtils.java line number 64
Matcher versionMatcher = VERSION_PATTERN.matcher(VERSION);
I am getting VERSION string 0.0

**Comment by Samikay** [comment]
Hey there, if you'd like this to work in the interim I've answered an SO post about the problem here: https://stackoverflow.com/questions/59243821/youtube-api-exception-in-initializer-error/59298544#59298544

And unfortunately, I duplicated this issue here if someone would like to decide which issue to close: https://github.com/googleapis/google-api-java-client/issues/1451

Cheers

**Comment by elharo** [comment]
This should be fixed in 1.30.7.

**Comment by adityabhaskar** [comment]
Still getting this error on `1.30.7` with `minifyEnabled`. Doesn't occur when `minifyEnabled` is set to false.

```
E: FATAL EXCEPTION: main
        Process: ..., PID: 9737
        java.lang.ExceptionInInitializerError
            at com.google.api.services.drive.Drive.<clinit>(SourceFile:48)
            at com.google.api.services.drive.Drive$Builder.build(SourceFile:9805)
            at g.a.a.k.d.a$a.a(SourceFile:55)
```            
            
Code where it occurs..
```            
                Drive.Builder(
                    NetHttpTransport(),
                    JacksonFactory(),
                    credential
                                )
                    .setApplicationName("...")
Line 55 ->>                    .build()
```

**Comment by elharo** [comment]
To be clear, it didn't whether minifyEnabled was true or false, right?

I'm not an Android expert so I need to dig into what minifyEnabled implies, but I'm guessing that it's somehow stripping code and removing code that is in fact accessed by reflection.

**Comment by elharo** [comment]
Bingo:

For most situations, the default ProGuard rules file (proguard-android- optimize.txt) is sufficient for R8 to remove only the unused code. However, some situations are difficult for R8 to analyze correctly and it might remove code your app actually needs. Some examples of when it might incorrectly remove code include:

    When your app calls a method from the Java Native Interface (JNI)
    When your app looks up code at runtime (such as with reflection)

Testing your app should reveal any errors caused by inappropriately removed code, but you can also inspect what code was removed by generating a report of removed code.

To fix errors and force R8 to keep certain code, add a -keep line in the ProGuard rules file. For example:

-keep public class MyClass

Alternatively, you can add the @Keep annotation to the code you want to keep. Adding @Keep on a class keeps the entire class as-is. Adding it on a method or field will keep the method/field (and its name) as well as the class name intact. Note that this annotation is available only when using the AndroidX Annotations Library and when you include the ProGuard rules file that is packaged with the Android Gradle plugin, as described in the section about how to enable shrinking.

There are many considerations you should make when using the -keep option; for more information about customizing your rules file, read the ProGuard Manual. The Troubleshooting section outlines other common problems you might encounter when your code gets stripped away.

**Comment by elharo** [comment]
The problem is from https://github.com/googleapis/google-api-java-client/pull/1452/files and I think this line in `GoogleUtils`:

```
InputStream inputStream =
      try (InputStream inputStream =
        GoogleUtils.class.getResourceAsStream("google-api-client.properties")) 
```

**Comment by elharo** [comment]
We should probably apply the annotation `androidx.annotation.Keep ` to GoogleUtils.

**Comment by elharo** [comment]
Meanwhile try adding

-keep public class com.google.api.client.googleapis.GoogleUtils

or some such thing to your proguard rules file.
